### ISSUE TITLE
The documentation doesn't tell how to activate the plugin

### ISSUE THREAD

**Issue by golddranks** [facelessuser/RawLineEdit#10]
The documentation doesn't tell how to activate the plugin. I installed it, but what to do next?

**Comment by facelessuser** [comment]
I mention what to do in under general usage: http://facelessuser.github.io/RawLineEdit/usage/#general-usage.  Is it possible you are new to Sublime and unfamiliar with some of the terminology?

**Comment by golddranks** [comment]
Oops, ignore that! Apparently I was blind. I'll close this.

**Comment by facelessuser** [comment]
No problem.
