### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by isapir** [facelessuser/RawLineEdit#12]
I am getting 404 from many links in README.md (e.g. https://github.com/facelessuser/RawLineEdit/tree/ST3), and can not find package RawLineEdit in Package Control as described at http://facelessuser.github.io/RawLineEdit/installation/

**Comment by facelessuser** [comment]
Yup, it's still alive.  I used to host images in a dropbox public folder, but dropbox  did away with the public folder.  Haven't gotten around to updating images in the repo.  It is on Package control: https://packagecontrol.io/packages/RawLineEdit.  Not sure why you aren't seeing it.

**Comment by isapir** [comment]
Sorry, apparently I have it already installed and that's the reason I didn't see it in the Package Control Install-list.

**Comment by facelessuser** [comment]
That will do it :wink:.
