### ISSUE TITLE
Document how to set up a key binding to activate/deactivate the plugin.

### ISSUE THREAD

**Issue by jarrodhroberson** [facelessuser/RawLineEdit#14]
I have been guessing at what the keybinding definition should look like and having no luck whatsoever.

 ```
 {
    "keys": [
      "ctrl+alt+l"
    ],
    "command": "??? what goes here ???",
  }
```

**Comment by Kotsuha** [comment]
It's `"toggle_raw_line_edit"`

**Comment by JedatKinports** [comment]
This should be added into the documentation: http://facelessuser.github.io/RawLineEdit/usage/

Key binding example:

`{ "keys": ["ctrl+shift+l"], "command": "toggle_raw_line_edit"  }`

Thanks @Kotsuha
