### ISSUE TITLE
Line endings become shown as <0x0d>¬

### ISSUE THREAD

**Issue by Kotsuha** [facelessuser/RawLineEdit#15]
I'm not sure when it happens. I noticed it after I upgraded to Sublime Text Build 3170.
The line endings become shown as `<0x0d>¬`.
![test](https://user-images.githubusercontent.com/10438710/39967037-a7c711c0-56e7-11e8-965c-1993d0fee333.png)
I have tried install RawLineEdit on a brand new Sublime Text Build 3170, still the same.

**Comment by facelessuser** [comment]
We were leveraging what Sublime used for carriage returns, by they generalized it for all unprintable characters. I have on my list to use phantoms, but haven't gotten around to it.

**Comment by facelessuser** [comment]
Closing this as this should get fixed with #17. Closing this issue.
