### ISSUE TITLE
Quick start guide missing from menu option

### ISSUE THREAD

**Issue by TCPhelps** [facelessuser/RawLineEdit#23]
After installing RawLineEdit, a new text window opens (with the title "Package Control Messages") with the message: 

> Welcome to RawLineEdit!  For a quick start guide, please go to   `Preferences->Package Settings->RawLineEdit->Quick Start Guide`

However, the Quick Start Guide is not one of the menu options and there is no information how to use the package.

**Comment by facelessuser** [comment]
Whoops! Yeah, there is a bit of copy and pasting for the general infrastructure of my projects. I did not actually implement a quick start guide for RawLineEdit yet.  I will update that.

@gir-bot add T: maintenance, C: docs
@gir-bot lgtm
