### ISSUE TITLE
[BUG] Viewing line endings more than once stacks line endings at the top

### ISSUE THREAD

**Issue by cturczynskyj** [facelessuser/RawLineEdit#27]
If you use "Raw Line Edit: View Line Endings" more than once on the same document, it adds line endings each time at the start of the document.

![image](https://user-images.githubusercontent.com/15792647/112674658-684fec80-8e23-11eb-8256-12a24815e603.png)

**Comment by facelessuser** [comment]
I'm not sure what you mean by `use "Raw Line Edit: View Line Endings" more than once on the same document`. Viewing doesn't edit the buffer, are you editing and saving, and then re-using again?

**Comment by facelessuser** [comment]
I just tested. I can edit and view fine. Please provide a step-by-step description.

@gir-bot add S: more-info-needed

**Comment by cturczynskyj** [comment]
Exact steps for me are:

1. open file in sublime text
2. command + shift + p to open package settings
3. Raw Line Edit: View Line Endings
4. Close the Line endings windows using Escape
5. Command + Shift + p to open package settings
6. Raw Line Edit: View Line Endings
7. Observe many extra line endings at the top of the RawLineEndings window

I spent a little more time with this and it looks like subsequent calls to view line endings adds as many line endings to the front of the RawLineEndings window as there were in the entire document previously. 

Example: 

Open file with 2x unix new line, and Raw Line Edit: View Line Endings
![image](https://user-images.githubusercontent.com/15792647/112701726-a7476780-8e4e-11eb-9768-b68928f9216f.png)

Close the RawLineEdit window, then Raw Line Edit: View Line Endings
![image](https://user-images.githubusercontent.com/15792647/112701741-add5df00-8e4e-11eb-8d04-dd03a8ab73a2.png)

**Comment by facelessuser** [comment]
Is this Sublime Text 3 or beta 4?

**Comment by facelessuser** [comment]
I've reproduced this bug. I look into a fix soon.

@gir-bot remove S: more-info-needed, S: triage
@gir-bot add T: bug, S: confirmed
