### ISSUE TITLE
Option to set default line endings

### ISSUE THREAD

**Issue by NetOperatorWibby** [facelessuser/RawLineEdit#28]
Ideally, this would be in `raw_line_edit.sublime-settings`. I'd prefer Unix by default but it looks like it's Windows.

**Comment by facelessuser** [comment]
I'm not sure what is being asked here.

> Ideally, this would be in raw_line_edit.sublime-settings. I'd prefer Unix by default but it looks like it's Windows.

What is Windows by default? RawLineEdit will read the raw file data (on storage) and show you what the line endings are. If you are viewing the data from an buffer not on disk, then it would be whatever the buffer is using per Sublime.

**Comment by NetOperatorWibby** [comment]
When I go into the dropdown menu I saw "Windows" selected but in hindsight, that might've just been the plugin telling me that the line endings were Windows-based.

No worries.
