### ISSUE TITLE
Doesn't work on files with invalid encoding

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [facelessuser/RawLineEdit#29]
I have a file with 104782 lines, and running `Raw Line Edit: View Line Endings` on the sublime text command pallete does not work. I've verified that RawLineEdit does work on small files.

**Comment by facelessuser** [comment]
This is kind of a vague statement. What do you mean by doesn't work? Do you mean it hangs (due to a gigantic buffer)? If so, I'd probably recommend you don't apply this to massive files, or if you do, be patient.

**Comment by facelessuser** [comment]
It might be possible to improve performance, but that would have to be investigated. Regardless of what we do, I suspect there will always be an upper limit when usage of the plugin becomes less practical.

**Comment by ItsIgnacioPortal** [comment]
> This is kind of a vague statement. What do you mean by doesn't work? Do you mean it hangs (due to a gigantic buffer)? If so, I'd probably recommend you don't apply this to massive files, or if you do, be patient.

To clarify this issue, I've recorded a video of the problem: https://youtu.be/ELWWdlPMsvc

**Comment by ItsIgnacioPortal** [comment]
Here's the console log:
```
DPI mode: per-monitor v2
startup, version: 4180 windows x64 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
application: /C/Program Files/Sublime Text
working dir: /C/Program Files/Sublime Text
packages path: /C/Users/User/AppData/Roaming/Sublime Text/Packages
state path: /C/Users/User/AppData/Roaming/Sublime Text/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/User/AppData/Roaming/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 5.53675
startup time: 5.77275
first paint time: 5.78075
reloading python 3.3 plugin AutoHotkey.ahkexec
reloading python 3.3 plugin Indent XML.indentxml
reloading python 3.3 plugin Indent XML.setup
reloading python 3.3 plugin Javascript Beautify.jsbeautify
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading python 3.3 plugin Minecraft Command Format.MinecraftCommandFormat
reloading python 3.3 plugin RawLineEdit.raw_line_edit
reloading python 3.3 plugin RawLineEdit.support
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading python 3.3 plugin RemoveNonAsciiChars.RemoveNonAscii
reloading plugin Default.run_syntax_tests
reloading python 3.3 plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Emmet.main
reloading plugin INI.open_context_reg_key
reloading plugin MarkdownEditing.plugin
reloading plugin Package Control.plugin
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
plugins loaded
Package Control: All specified packages up-to-date!
git: using configuration from C:\Program Files\Git\cmd\git.exe
git: tracking working dir C:\Users\User\Documents\Github\SecLists-Express
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\RawLineEdit.sublime-package\raw_line_edit.py", line 460, in popup_rle
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\RawLineEdit.sublime-package\raw_line_edit.py", line 521, in show_rle
  File "./python3.3/codecs.py", line 691, in read
  File "./python3.3/codecs.py", line 494, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 2427692: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1488, in run_
    return self.run(edit)
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\RawLineEdit.sublime-package\raw_line_edit.py", line 578, in run
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\RawLineEdit.sublime-package\raw_line_edit.py", line 462, in popup_rle
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\RawLineEdit.sublime-package\raw_line_edit.py", line 521, in show_rle
  File "./python3.3/codecs.py", line 691, in read
  File "./python3.3/codecs.py", line 494, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 2427692: invalid start byte
```

**Comment by facelessuser** [comment]
Seems like an encouraging problem. What encoding is your file using?

**Comment by ItsIgnacioPortal** [comment]
> Seems like an encouraging problem. What encoding is your file using?

On sublime text it's opened with the encoding UTF-8. I didn't make the file manually, it's automatically updated by a multitude of scripts.

This is the file that triggers the issue: https://github.com/ItsIgnacioPortal/SecLists-Express/raw/feafa59448e620ea8d398999e2124fdff60c6d6d/Discovery/Web-Content/trickest-robots-disallowed-wordlists/top-10000.txt

**Comment by facelessuser** [comment]
Okay, I'll take a look and see if I can identify the issue.

**Comment by facelessuser** [comment]
Yep, it's some kind of encoding problem. Sublime reports UTF-8, we assume it is correct, we try and parse with UTF-8, and it breaks. I tried to open a Python session and read the file, it breaks:

```py
>>> import codecs
>>> f = codecs.open('top-10000.txt', 'r', encoding='utf-8')
>>> f.read()
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    f.read()
    ~~~~~~^^
  File "<frozen codecs>", line 710, in read
  File "<frozen codecs>", line 510, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 2427692: invalid start byte
```

**Comment by facelessuser** [comment]
Interestingly, yes, Sublime opens the file just fine, but once I save the file in Sublime, it then works in RawLineEdit. So Sublime reads it in, but when you save it, something changes which allows us to parse it.

If I compare both files (after Sublime alters it and before)

<img width="1204" alt="Screenshot 2024-11-20 at 11 34 18 AM" src="https://github.com/user-attachments/assets/a94f3e41-9199-48c4-b552-d2835b74c47c">

Interestingly, it looks like in the diff tool, it maybe isn't rendering those characters and is instead using a question mark Unicode character to denote a fallback rendering for problematic characters. Sublime seems to turn those into normal question marks.

If we view this in hex, it appears the characters are more complex (on the right), but just are all getting rendered as Unicode fallback question marks, and it shows (on the left) Sublime is converting it to ASCII question marks. But once that is done, we can process the file.

<img width="1270" alt="Screenshot 2024-11-20 at 11 46 22 AM" src="https://github.com/user-attachments/assets/f547556c-a212-4dad-8629-3042450fdce7">

**Comment by facelessuser** [comment]
As far as I can tell, the file is not a proper UTF-8 file. Most edtors and such when determining a file's encoding will only look at small amount at the start of the file as it is not very performant to analyze the entire file. So they will look at a chunk larger enough to know with pretty good certainty what the file's encoding is. But it also isn't uncommon, as this approach is not perfect, to then enable a mode where unrecognized characters are just converted to something like `�`. Some, like Sublime, may even use an ASCII `?`.

Rawline Edit does not do this, but we could. Keep in mind though, that if we did this, it would be a destructive process, much like what Sublime is doing. It would alter the original content outside of just handling line endings.
