### ISSUE TITLE
Color theme disabled when viewing

### ISSUE THREAD

**Issue by mhulse** [facelessuser/RawLineEdit#3]
Cool plug! Thanks.

When viewing line endings, my code coloring turns to white (no syntax highlighting). Is this normal?

Also, is there any way to have line endings displayed all the time?

Thanks! :octocat:

**Comment by Kristinita** [comment]
@facelessuser , do you plane non-disable active color scheme?

Thanks.

**Comment by facelessuser** [comment]
Maybe.  Injecting glyphs would break some schemes, but I've thought about using phantoms which would allow injecting glphys without actually altering the buffer.  Looking into this is extremely low priority, but I've thought about it.
