### ISSUE TITLE
Does not work in ST3 build 3125

### ISSUE THREAD

**Issue by kindkaktus** [facelessuser/RawLineEdit#9]
Just installed the plugin on ST3 build 3125 from package control. Restarted ST. The plugin shows up under Preferences -> Package Settings, with default configuration:
"use_sub_notify": true,
"use_newline_glyph": true,
 "use_raw_line_edit_theme": true,
 "view_only": false,
 "operate_on_unsaved_buffers": false

No line endings are displayed.

Windows 7 Professional x64

Please lemme know if you need more info for debugging the issue.

**Comment by facelessuser** [comment]
Maybe check out issue #6 and see if that answers your question.

**Comment by kindkaktus** [comment]
Thanks, this explains the thing.
